
package code;

import java.awt.CardLayout;

/**
 *
 * @author Aluno
 */
public class Painel extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    
    private ManterDepartamento manterDept;
    private ManterFuncionario manterFunc;
    private Pagamentos manterPag;
    private Devs manterDev;
    
    public Painel() {
        initComponents();
        manterDept = new ManterDepartamento();
        manterFunc = new ManterFuncionario();
        manterPag = new Pagamentos();
        manterDev = new Devs();
        panelManter.setLayout(new CardLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDoBotaoManterFechar = new javax.swing.JPanel();
        btnFecharPanelManter = new javax.swing.JButton();
        panelManter = new javax.swing.JPanel();
        jHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuManter = new javax.swing.JMenu();
        menuDepartamento = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Devs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFecharPanelManter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnFecharPanelManter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPanelManterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDoBotaoManterFecharLayout = new javax.swing.GroupLayout(panelDoBotaoManterFechar);
        panelDoBotaoManterFechar.setLayout(panelDoBotaoManterFecharLayout);
        panelDoBotaoManterFecharLayout.setHorizontalGroup(
            panelDoBotaoManterFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoBotaoManterFecharLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFecharPanelManter)
                .addContainerGap())
        );
        panelDoBotaoManterFecharLayout.setVerticalGroup(
            panelDoBotaoManterFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoBotaoManterFecharLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnFecharPanelManter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelManter.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotipo.png"))); // NOI18N

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jButton1.setText("ACESSAR");

        javax.swing.GroupLayout jHomeLayout = new javax.swing.GroupLayout(jHome);
        jHome.setLayout(jHomeLayout);
        jHomeLayout.setHorizontalGroup(
            jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomeLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomeLayout.createSequentialGroup()
                        .addGroup(jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2))
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomeLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))))
        );
        jHomeLayout.setVerticalGroup(
            jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelManter.add(jHome);

        menuManter.setText("Menu");

        menuDepartamento.setText("Departamento");
        menuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepartamentoActionPerformed(evt);
            }
        });
        menuManter.add(menuDepartamento);

        menuFuncionario.setText("Funcionario");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        menuManter.add(menuFuncionario);

        menuPagamento.setText("Pagamento");
        menuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagamentoActionPerformed(evt);
            }
        });
        menuManter.add(menuPagamento);

        jMenuBar1.add(menuManter);

        jMenu2.setText("Sobre");

        Devs.setText("Devs");
        Devs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevsActionPerformed(evt);
            }
        });
        jMenu2.add(Devs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDoBotaoManterFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelManter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDoBotaoManterFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelManter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepartamentoActionPerformed
        // TODO add your handling code here:
        panelManter.add(manterDept, "manterDept");
        ((CardLayout)panelManter.getLayout()).show(panelManter, "manterDept");
        this.revalidate();
        jHome.setVisible(false); 
        manterDept.setVisible(true);  
    }//GEN-LAST:event_menuDepartamentoActionPerformed

    private void btnFecharPanelManterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPanelManterActionPerformed
        // TODO add your handling code here:
        panelManter.removeAll();
        panelManter.revalidate();
        panelManter.repaint();
    }//GEN-LAST:event_btnFecharPanelManterActionPerformed

    private void DevsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevsActionPerformed
        // TODO add your handling code here:
        panelManter.add(manterDev, "manterDev");
        ((CardLayout)panelManter.getLayout()).show(panelManter, "manterDept");
        this.revalidate();
        jHome.setVisible(false); 
        manterDev.setVisible(true); 
    }//GEN-LAST:event_DevsActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        // TODO add your handling code here:
        panelManter.add(manterFunc, "manterFunc");
        ((CardLayout)panelManter.getLayout()).show(panelManter, "manterFunc");
        this.revalidate();
        jHome.setVisible(false); 
        manterFunc.setVisible(true); 
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void menuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagamentoActionPerformed
        // TODO add your handling code here:
        panelManter.add(manterPag, "manterPag");
        ((CardLayout)panelManter.getLayout()).show(panelManter, "manterPag");
        this.revalidate();
        jHome.setVisible(false); 
        manterPag.setVisible(true); 
    }//GEN-LAST:event_menuPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Devs;
    private javax.swing.JButton btnFecharPanelManter;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem menuDepartamento;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenu menuManter;
    private javax.swing.JMenuItem menuPagamento;
    private javax.swing.JPanel panelDoBotaoManterFechar;
    private javax.swing.JPanel panelManter;
    // End of variables declaration//GEN-END:variables
}
